global:
  smtp_smarthost: '${SMTP_HOST:-localhost:587}'
  smtp_from: '${ALERT_FROM_EMAIL:-alerts@sleepr.local}'
  smtp_auth_username: '${SMTP_USERNAME:-}'
  smtp_auth_password: '${SMTP_PASSWORD:-}'
  smtp_require_tls: true

  # Slack webhook URL for notifications
  slack_api_url: '${SLACK_WEBHOOK_URL:-}'

templates:
- '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'severity', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 5s
    repeat_interval: 5m
  - match:
      severity: warning
    receiver: 'warning-alerts'
    repeat_interval: 15m
  - match:
      service: business
    receiver: 'business-alerts'
    repeat_interval: 30m

receivers:
- name: 'default-receiver'
  email_configs:
  - to: '${DEFAULT_ALERT_EMAIL:-admin@sleepr.local}'
    subject: '[Sleepr] Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
      {{ end }}

- name: 'critical-alerts'
  email_configs:
  - to: '${CRITICAL_ALERT_EMAIL:-admin@sleepr.local}'
    subject: '[CRITICAL] Sleepr Alert: {{ .GroupLabels.alertname }}'
    body: |
      🚨 CRITICAL ALERT 🚨
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      Severity: {{ .Labels.severity }}
      Started: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts-critical'
    color: danger
    title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *{{ .Annotations.summary }}*
      {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: '${WARNING_ALERT_EMAIL:-admin@sleepr.local}'
    subject: '[WARNING] Sleepr Alert: {{ .GroupLabels.alertname }}'
    body: |
      ⚠️ WARNING ⚠️
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      {{ end }}
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts-warning'
    color: warning
    title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      {{ .Annotations.summary }}
      {{ .Annotations.description }}
      {{ end }}

- name: 'business-alerts'
  email_configs:
  - to: '${BUSINESS_ALERT_EMAIL:-business@sleepr.local}'
    subject: '[Sleepr Business] {{ .GroupLabels.alertname }}'
    body: |
      📊 Business Metric Alert
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#business-metrics'
    color: good
    title: '📊 Business Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      {{ .Annotations.summary }}
      {{ .Annotations.description }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'service']
